# Generated by Django 4.1.7 on 2023-04-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_movie_rating_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
